# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-20 10:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('profile_id', models.CharField(max_length=36, unique=True)),
            ],
        ),
    ]
