# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-20 18:31
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(null=True)),
                ('date', models.DateField(null=True)),
                ('stages', models.TextField(choices=[('Series A', 'Series A'), ('Series B', 'Series B'), ('Series C', 'Series C'), ('Series D', 'Series D'), ('Series E', 'Series E')])),
                ('investors', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255, null=True)),
                ('phone_number', models.IntegerField(null=True)),
                ('linkedin', models.TextField(max_length=255, null=True)),
                ('twitter', models.TextField(max_length=255, null=True)),
                ('facebook', models.TextField(max_length=255, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='founded_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='company',
            name='markets',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100, null=True), null=True, size=None),
        ),
        migrations.AddField(
            model_name='company',
            name='website',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='social',
            name='company_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='social', to='company.Company'),
        ),
        migrations.AddField(
            model_name='funding',
            name='company_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fundings', to='company.Company'),
        ),
    ]
